# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
kotlin.code.style=official

# Desactivar Kotlin integrado de AGP 9 para permitir compatibilidad con KSP
android.builtInKotlin=false
android.newDsl=false

# Compatibilidad de KSP e incremental
ksp.use.classpath.snapshot=false
ksp.incremental=false
kotlin.incremental=false
